---

- name: ELASTICSEARCH REDHAT | Add external repository
  yum_repository:
    baseurl: "{{ item.url }}"
    description: "{{ item.description }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    reposdir: "{{ item.reposdir }}"
  loop: "{{ elasticsearch_redhat_repository }}"

- name: ELASTICSEARCH REDHAT | Install packages
  package:
    name: elasticsearch-oss
    update_cache: yes
    state: present
